### ISSUE TITLE
Question on experiment setting

### ISSUE THREAD

**Issue by Isabellalli** [zqhang/MTGFLOW#7]
I have a question regarding the experimental section of the paper. How were the experimental data in Table 1 obtained? Were they calculated through several random sets of experiments? How many seeds were used for each set of calculations

**Comment by zqhang** [comment]
We described the data split for training and testing in Section Experiment, and reported the results of each dataset over five runs using different seeds.

**Comment by Isabellalli** [comment]
> We described the data split for training and testing in Section Experiment, and reported the results of each dataset over five runs using different seeds.
> 
> As for other experiment details, please take a look at the Section Experiment and refer to the code provided in this repo.

Are the five rounds of experiments conducted with five seeds each, using the checkpoint from the training results for testing? Or is it that five seeds are randomly selected, and after training with each seed, a test is performed? Mainly, I repeated the experiment, but the results did not reach the effects shown in Table 1, so I am quite puzzled.

**Comment by zqhang** [comment]
We report results using the latter method. We test the performance after every epoch and report the best test performance among them. Could you reproduce the reported results using the given weights in this repo? We use seeds ranging from approximately 15 to 20 or 20 to 25 because I cannot remember accurately.

**Comment by Isabellalli** [comment]
> We report results using the latter method. We test the performance after every epoch and report the best test performance among them. Could you reproduce the reported results using the given weights in this repo? We use seeds ranging from approximately 15 to 20 or 20 to 25, and I cannot remember accurately.

Thank you for your reply. I tried seeds 15-20 based on this repo, the results were not very good. I am now planning to try seeds 20-25
